### ISSUE TITLE
Edits via Email

### ISSUE THREAD

**Issue by roshni-addweb** [snehal-addweb/Mortgagespeak#56]
1. The daily newsletter shows "username" when it should show the user's "first name".
   => Working fine from my end. Please provide "username" for which you are facing problem.
2. The ability to show the "Advertising" and "Newsletter" forms (via User profile > roles) doesn't enable forms
   see
   un: Molly@MercuryVMP.com
   pw: MercuryVMP73114
   => Working fine from my end. PFA screenshots.

![newsletter_form](https://cloud.githubusercontent.com/assets/14847556/16268386/e14d398a-38ab-11e6-835a-0b6b63eac6e6.png)

![advertise_form](https://cloud.githubusercontent.com/assets/14847556/16268417/fce4fdcc-38ab-11e6-8d77-f3b373bf6765.png)

Question:
1. For the company images shown in the client newsletter, where is the file location to upload or edits these logos? Many images aren't showing.
=> You will see list of company from here : http://mortgagespeak.com/admin/structure/taxonomy/company_tags
=> Please edit the term and upload image in "Large Logo" field.

Let me know in case of any query or concern. Thanks

**Comment by gatsby8870** [comment]
**1. Forms Not Showing**: Kindly clear your cache and try again to view the user's page. Attached are screenshots from browsers Chrome, FireFox, Internet Explorer 11 and Safari all showing the form missing

**2. Company Logos Missing**: Upon research, the issue is when there is more than one company tagged to the content, the system does not pull either logo. At this time, ok to disregard as I do not know the solution at this point.

![no-form---chrome](https://cloud.githubusercontent.com/assets/18587752/16283901/6d05a8c6-3894-11e6-9897-7aeefb50ce4a.png)
![no-form---firefox](https://cloud.githubusercontent.com/assets/18587752/16283902/6d068fca-3894-11e6-922e-24de204e6a82.png)
![no-form---ie-11](https://cloud.githubusercontent.com/assets/18587752/16283903/6d0b4d76-3894-11e6-89a5-355e3c9b716c.png)
![no-form---safari](https://cloud.githubusercontent.com/assets/18587752/16283929/942c491e-3894-11e6-9d03-9c299f9768d3.png)

**Comment by Krina-Addweb** [comment]
Hello Greg , 
Following are the inputs for both the issues : 
1) Forms Not Showing: Kindly clear your cache and try again to view the user's page. Attached are screenshots from browsers Chrome, FireFox, Internet Explorer 11 and Safari all showing the form missing >> Please test this functionality on http://mortgagespeak.com/user/272/edit ( un: Molly@MercuryVMP.com , pw: MercuryVMP73114) page where you can see the Advertising" and "Newsletter" forms (via User profile > roles) forms.
![image](https://cloud.githubusercontent.com/assets/14847553/16305659/726deb22-3978-11e6-955a-2e431f4d19c4.png)

2)  Company Logos Missing: Upon research, the issue is when there is more than one company tagged to the content, the system does not pull either logo. At this time, ok to disregard as I do not know the solution at this point. >> Done

**Comment by gatsby8870** [comment]
1. Forms Not Showing. You are absolutely right. This was my mistake. I was looking for it in the "My Page" area when it is within the "User Profile". My apologies and thank you!
