### ISSUE TITLE
"Daily Newsletter" edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#64]
Hello, may I have an estimate for completing the below edits to my "Daily Newsletter"? (non client newsletter)

Please refer to the attached image for reference.

**Change:**
Background color to:            f2f2f2
Newsletter border color to:     cccccc
Text font color to:                 444444

**Misc:**
Add logo and name (hyperlink to here), and "date" in top "header" area
Newsletter font size: 14 Arial, spacing AV<> 75; see image
Display user's first name shown. Still shows "username". Now I use "Rick" just as example.
Add my picture below (I will send you mine later. This is not me.)
Big blue button links to "My Page"
Add my site's web location and keep hyperlinked document already in Daily Newsletter

**Notes:**
Line spacing might be 1.25 in image

![daily-newsletter](https://cloud.githubusercontent.com/assets/18587752/17383507/e7927d94-599b-11e6-83d3-1fe0eb7ca68e.png)

**Comment by saurabhd** [comment]
My Estimates: 8 working hours.

Let me know your thoughts.

**Comment by gatsby8870** [comment]
Please begin this project.

I updated the image and please follow the below items. 1 new image attached.

Notes:
- Font size:        15
- Font stye:        Arial
- Color:        4444
- Character spacing:    50

Misc:
- (top) Logo and My Site's name hyperlinks to my home page: www.MortgageSpeak.com
- The big blue button links to:             www.mortgagespeak.com/my-page/tracked-news
- The "+Upload" text links to:              http://mortgagespeak.com/upload
- The "+Upload" text font size is:          12
- In signature line, my site's url is hyperlinked to:   www.MortgageSpeak.com
- In Signature line, the sponsored' document links to:  http://www.mortgagespeak.com/effective-promotion-white-paper
- Hyperlinks have no underline shown but do on mouseover
- Email background color is as on image:          f2f2f2
- Border color is:                            cccccc
- Picture box is:   100w X 100H
- The newsletter should use user's first name. Not username. It's coded for username.
- "Questions? Contact Us" can stay as currently linked
- "Unsubscribe" link comes from Drupal automatically
- The text in the email should update to show correct Day of Week, Month Date, Year.

![daily-newsletter-edit](https://cloud.githubusercontent.com/assets/18587752/17421269/3cf3054c-5a6e-11e6-827d-4b95c51a46eb.png)

**Comment by saurabhd** [comment]
Hello Greg, 

Thanks for sharing the details, work is in progress. 

Happy Weekend!!

**Comment by saurabhd** [comment]
Hello Greg,

This task would take more 3 hours, need your approval. 

Here's the tasklist for extra hours:
- Button issue 'Click Here For The Latest News and Information' in Outlook software
- Issue of full width of content area for i-phone 6 plus
- Blue border  of user image

**Comment by gatsby8870** [comment]
Ok on the additional hours. 

Thanks!

**Comment by Krina-Addweb** [comment]
1)(top) Logo and My Site's name hyperlinks to my home page: www.MortgageSpeak.com
=> Done
2) The big blue button links to: www.mortgagespeak.com/my-page/tracked-news
=> Done
3) The "+Upload" text links to: http://mortgagespeak.com/upload
=> Done
4) The "+Upload" text font size is: 12
=> Done
5) In signature line, my site's url is hyperlinked to: www.MortgageSpeak.com
=> Done
6) In Signature line, the sponsored' document links to: http://www.mortgagespeak.com/effective-promotion-white-paper
=> Done
7) Hyperlinks have no underline shown but do on mouseover
=> Done ( Underlined hyperlinks would only displayed in site Newsletters .  It would not be displayed in the Email template as it is not feasible)
8) Email background color is as on image: f2f2f2
=> Done
9) Border color is: cccccc
=> Done
10) Picture box is: 100w X 100H
=> Done
11) The newsletter should use user's first name. Not username. It's coded for username.
=> Done (It is working fine from our end, please check that you have selected Daily newsletter category as we have implemented for that only.)
12) "Questions? Contact Us" can stay as currently linked
=> Done
13) "Unsubscribe" link comes from Drupal automatically
=> Yes
14) The text in the email should update to show correct Day of Week, Month Date, Year.
=> Done (On creation of "Daily newsletter" in a site it displays #currentdate# instead of Day of Week, Month Date, Year. And once you send it to the user it would be replaced by sending newsletter date instead of  #currentdate#.)

**Comment by gatsby8870** [comment]
![listed-twice](https://cloud.githubusercontent.com/assets/18587752/17539175/9ecac99c-5e71-11e6-92c4-9ab062077438.png)
Hello, here are some edits:
1. Change blue button hyperlink to this page:       http://mortgagespeak.com/news
2. Change bold text "updated" to bold "updated with new content"
3. Change button image of text to actual text; image font looks blurry vs real text
4. Change text to:                  "Click To Continue"
5. Add a "period" (e.g. ".") after user first name field. For example, "Hi, Greg."
6. Move "+ Upload" from top right to lower area with "Contact Us" link
7. Edit lower area links from "Questions? Contact Us" to "+ Upload  |  Contact Us"
8. Make this vertical line color #CCCCCC (between Upload and Contact Us)
9. In web email clients, it shows the name of the newsletter twice in the in-bin and top of mail

![daily-newsletter-edit-8-9-16](https://cloud.githubusercontent.com/assets/18587752/17539115/2c2fb168-5e71-11e6-8197-30945edc629f.png)

**Comment by Krina-Addweb** [comment]
Hello Greg,

All above mentioned points are done.

Thanks.

**Comment by gatsby8870** [comment]
Hello. The work is looking great so far. Thanks for your terrific help!

Here are some additional edits:
1. Please use the attached image as the image to use within the box
2. Link my picture to this webpage: www.linkedin.com/in/gregory-janecka
3. Add mouseover text for photo to state: "Let's connect on LinkedIN."

1 attachment

Thank you!

![greg-newsletter-picture](https://cloud.githubusercontent.com/assets/18587752/17602649/29e96a12-5fd3-11e6-8277-165921ab2de3.png)

**Comment by Krina-Addweb** [comment]
Hello Greg,
Above Mentioned changes are done. Please Check.
Thanks.

**Comment by saurabhd** [comment]
@gatsby8870 please close this ticket and other as well if they are completed.

**Comment by gatsby8870** [comment]
This looks fine except the text name adjacent my logo (MortgageSpeak) looks blurry. The image quality of the text image is not high like in the image I provided.

Attached is the image showing the higher quality.

This update header should be used for the new "Daily Newsletter" as well.

Here is the image file location: http://www.mortgagespeak.com/sites/default/files/dailylogo.png

Thank you!

![email-header](https://cloud.githubusercontent.com/assets/18587752/17719587/4fc4f640-63e1-11e6-938b-48f46ada9c35.jpg)

**Comment by Krina-Addweb** [comment]
Hi Greg,

Please check the last mentioned comment.

Thanks
