### ISSUE TITLE
Estimate Request: New ad placement on Splash Page

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#87]
I would like an estimate on adding an advertisement to the "splash" page shown on app load. This splash splash page loads for about 3 seconds.

My thoughts are to:

1. - Extend the splash page display to 5 seconds
2. - Show the existing splash page now (no ad) for 2 seconds
3. - After 2 seconds, display a Drupal ad at the bottom of the splash page for 3 seconds with small text above it stating "Presented by:"
4. - Then proceed to News page as already coded

Here is an example from another app which gave me the idea. See green arrow.

![bleacher-report-splash-page](https://cloud.githubusercontent.com/assets/18587752/24655134/8e901194-1902-11e7-8c3f-0719549118dc.png)

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

I have reviewed your requirement.

The splash screen is just an image which greets the user who is going to use your application. It does not contain anything on it.

But what you are asking and displaying in the above mentioned image is something which can be doable. For that we need to create one whole page and need to make it behave like the splash screen and need to remove the actual splash screen and on that newly page we can display the advertisement as per your requirement.

Total estimate for doing above mentioned process is **10 Hours.**

Estimation includes:
- Adding new page to the application.
- Need to design the page so that it looks similar to the splash screen.
- Adding advertisement on that page.
- Testing.

Please let me know your thoughts on this.

**Comment by gatsby8870** [comment]
This is approved.

Thank you.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

One doubt we have while working on this, Do we need to display Drupal ads on the splash screen or the Google ads? As per your comment we need to display Drupal ads, if this is the case then please let us know ads from which page we need to show there. We need to show ads from Editor pics or from News or from P.R or from Podcast?

**Comment by gatsby8870** [comment]
Hi, at this point, just Drupal ads.

In the future, it will be a combination but we can address it then.

Thanks.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

Thanks for your answer.

Now, which Drupal ad I need to show there? I mean, do you create a separate ad for splash screen like you have added for News and Editor pics?

Please let us know so that we can get it done quickly.

If you have any doubt, then we can talk on Skype chat.

**Comment by gatsby8870** [comment]
Separate ad.

It will be about half as tall (height). Use the height of the ad in the above sample shown next to the green arrow as the approximate height of the new ad.

Thanks.

**Comment by gatsby8870** [comment]
Hello,

Here is the edit to the page I mentioned earlier. I wanted to:

1. Move the "PRESENTED BY :" text and ad DOWN.
2. Increase the margin after the text "PRESENTED BY :" and the new ad below
3. Make the text "PRESENTED BY :" in italics, move the colon after "BY :" right after the "Y" to be like this "BY:"
4. Make the "PRESENTED BY :" text lower case like this "Presented by:"

See attached image to use as your guide.

![screenshot-ad-moved-down](https://cloud.githubusercontent.com/assets/18587752/24988460/beebf8ce-1fcb-11e7-83a6-ca2e00806dee.png)
